name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  ##the next line creates the global variable "global_env" and initializes it with word "global"
env:
  global_env: global

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sys_info"(name of job)
  sys_info:
    runs-on: ubuntu-latest
    ##This expression creates the local variable "local_env" and initializes it with 
    ##the global variable of step name GITHUB_JOB
    env:
      local_env: job
      
    steps:
      - name: check tools
        run: g++ -v
      - name: cmake check  
        run: cmake --version
      
      - name: Setup Ninja
    # You may pin to the exact commit or the version.
    # uses: ashutoshvarma/setup-ninja@93f8b9763516f1fb9b4d9840b12d844bee17791f
        uses: ashutoshvarma/setup-ninja@v1.1
        
          
  build:
    needs: [sys_info]
    runs-on: ubuntu-latest
#     env:
#       local_env: ImageOS
    steps:
      ##we need the next expression to download the latest version of our repository
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build
          cmake ninja ..
          cmake --build .
          cd ..
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: my_app
          path: ./build/src/main, ./build/src/example.html
